<?php

namespace Modules\Ledger\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use DB;

class LedgerDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       // Model::unguard();

        DB::table('local_node')->insert([

                [
                    'name' => 'Amsterdam',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Barcelona',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Berlin',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                 [
                    'name' => 'Bologna',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Firenze',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'France (Scattered)',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Genève',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Genova',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ], 
                [
                    'name' => 'Granada',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],                 
                 [
                    'name' => 'Istria',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Italy (Scattered)',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Malaga',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Marseille',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Napoli',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Paris',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Pisa',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Porto',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Roma',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Sierra de São Mamede',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Spain (Scattered)',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'València',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Venice',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Vienna',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'name' => 'Vlaanderen',
                    'description' => '',
                    'status' => 'Active',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                  
            ]);
           DB::table('local_node_geos')->insert([

                [                    
                    'local_node_id' => 1,
                    'city_id'        => 29,
                    'department_id'  => null,
                    'area_id'        => 20,
                    'country_id'     => 8,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 1,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 20,
                    'country_id'     => 8,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 1,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 8,
                    'responsibility' => 'Third',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 2,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 30,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 3,
                    'city_id'        => 48,
                    'department_id'  => null,
                    'area_id'        => 32,
                    'country_id'     => 11,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 4,
                    'city_id'        => 4,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 4,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 4,
                    'country_id'     => 2,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 5,
                    'city_id'        => 168,
                    'department_id'  => null,
                    'area_id'        => 45,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 6,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 1,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 8,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 8,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 18,
                    'country_id'     => 2,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                 [                    
                    'local_node_id' => 7,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 85,
                    'country_id'     => 19,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 9,
                    'city_id'        => null,
                    'department_id'  => 125,
                    'area_id'        => 31,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Excluding',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 9,
                    'city_id'        => null,
                    'department_id'  => 40,
                    'area_id'        => 31,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 9,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 31,
                    'country_id'     => 12,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 10,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 302,
                    'country_id'     => 22,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 11,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 12,
                    'city_id'        => null,
                    'department_id'  => 125,
                    'area_id'        => 31,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 13,
                    'city_id'        => 49,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 1,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                 [                    
                    'local_node_id' => 13,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 33,
                    'country_id'     => 1,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 14,
                    'city_id'        => 222,
                    'department_id'  => 152,
                    'area_id'        => 111,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 15,
                    'city_id'        => 7,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 1,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 15,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 1,
                    'country_id'     => 1,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 16,
                    'city_id'        => null,
                    'department_id'  => 355,
                    'area_id'        => 45,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 16,
                    'city_id'        => 168,
                    'department_id'  => null,
                    'area_id'        => 45,
                    'country_id'     => 2,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Excluding',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 17,
                    'city_id'        => 50,
                    'department_id'  => null,
                    'area_id'        => 34,
                    'country_id'     => 7,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 17,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 34,
                    'country_id'     => 7,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 17,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 300,
                    'country_id'     => 7,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 18,
                    'city_id'        => 3,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 18,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 3,
                    'country_id'     => 2,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 19,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 88,
                    'country_id'     => 7,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 20,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 21,
                    'city_id'        => 45,
                    'department_id'  => null,
                    'area_id'        => 29,
                    'country_id'     => 12,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 21,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 29,
                    'country_id'     => 12,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 22,
                    'city_id'        => 2,
                    'department_id'  => null,
                    'area_id'        => 2,
                    'country_id'     => 2,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 22,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 2,
                    'country_id'     => 2,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                 [                    
                    'local_node_id' => 23,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 114,
                    'country_id'     => 32,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                 [                    
                    'local_node_id' => 24,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => 17,
                    'country_id'     => 6,
                    'responsibility' => 'Primary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [                    
                    'local_node_id' => 24,
                    'city_id'        => null,
                    'department_id'  => null,
                    'area_id'        => null,
                    'country_id'     => 6,
                    'responsibility' => 'Secondary',
                    'incl_excl'      => 'Including',
                    'geo_level'      => null,
                    'zip'            => null,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],

                 
                  
            ]);

        // $this->call("OthersTableSeeder");
    }
}
